import './globals.css';
import { Providers } from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/furo-yellow.svg" sizes="32x32" />
      </head>
      <body className={`antialiased sm:overflow-hidden overflow-auto`}></body>
    </html>
  );
}
